Issue fixes
taikoxyz/taiko-mono pull request #12368
Opened 2023-01-10 08:38 UTC by shadab-taiko

Fixes
- #9046
- #9147 (will have to check with the reporter of the issue if this is fixed)
- #9058

2023-01-10 14:29 UTC, cyberhorsey requested changes

2023-01-10 14:29 UTC, cyberhorsey commented on packages/bridge-ui/src/components/buttons/SelectToken.svelte
> +  let dropdownElement;
Missing type annotation

2023-01-10 14:29 UTC, cyberhorsey commented on packages/bridge-ui/src/components/ButtonWithTooltip.svelte
> +  export let onClick;
Missing type annotation
export let onClick: () => void;

2023-01-10 14:37 UTC, d1onys1us approved these changes, later dismissed

2023-01-11 11:28 UTC, dantaik approved these changes

2023-01-11 14:58 UTC, RogerLamTd approved these changes

2023-01-12 21:02 UTC, cyberhorsey approved these changes

2023-01-12 21:02 UTC, merged