fix(protocol): Several protocol fixes.
taikoxyz/taiko-mono pull request #13034
Opened 2023-01-24 08:00 UTC by cyberhorsey

1) Introduction of `blockHashHistory` has broken `getLatestSyncedHeader`, which returns the zero address after the first iteration through blockHashHistory.

2) `verifyBlocks` max num blocks arg always verified 1 more than the block numbes specified. ie: passing in `1` verified `2`.

2023-01-24 10:05 UTC, davidtaikocha commented on packages/protocol/contracts/L1/libs/LibVerifying.sol
> +            i < state.nextBlockId && processed < maxBlocks;
looks like changing `<=` to `<` is enough to fix the issue? no need to additionally pass `config.maxVerificationsPerTx + 1` as `maxBlocks`?

2023-01-24 10:13 UTC, dantaik requested changes

2023-01-24 10:13 UTC, dantaik commented on packages/protocol/contracts/L1/TaikoL1.sol
> +            maxBlocks: config.maxVerificationsPerTx + 1,
shall we change the code inside `LibVerifying.verifyBlocks` from:

```
processed <= maxBlocks;
```
to
```
processed < maxBlocks;
```

2023-01-24 22:18 UTC, dantaik approved these changes, later dismissed

2023-01-24 22:49 UTC, dantaik commented on packages/protocol/contracts/L1/TaikoL1.sol
> +            state.getL2BlockHash(
https://github.com/taikoxyz/taiko-mono/pull/13042

@cyberhorsey I think we need the fix as above.

2023-01-25 02:02 UTC, dantaik approved these changes

2023-01-25 09:23 UTC, davidtaikocha approved these changes

2023-01-25 13:48 UTC, dantaik approved these changes

2023-01-25 13:48 UTC, merged