test(protocol): integration tests for isMessageFailed
taikoxyz/taiko-mono pull request #13072
Opened 2023-01-29 20:18 UTC by RogerLamTd

2023-02-08 01:03 UTC, cyberhorsey commented
@RogerLamTd any update on this?

2023-02-08 01:15 UTC, RogerLamTd commented
> @RogerLamTd any update on this?

Working with David on some issues, managed to start the geth node instead but since they're both --dev nodes they are defaulted to chainId 1337 which causes issues; may want to add a check for duplicate chain IDs in the future as well if it's an edge case. Trying to figure out a way to start one with a custom chainId, and a couple other issues

2023-02-08 13:19 UTC, davidtaikocha commented
> > @RogerLamTd any update on this?
> 
> Working with David on some issues, managed to start the geth node instead but since they're both --dev nodes they are defaulted to chainId 1337 which causes issues; may want to add a check for duplicate chain IDs in the future as well if it's an edge case. Trying to figure out a way to start one with a custom chainId, and a couple other issues

pushed a new commit to fix your issues, plz try again.

2023-02-10 17:27 UTC, RogerLamTd commented
Reverted bridge changes mean all bridge tests work fine now, but TaikoL1 tests are having trouble on the l2 geth node changes. Still investigating but would appreciate any help!

2023-02-14 00:18 UTC, cyberhorsey requested changes

2023-02-14 00:18 UTC, cyberhorsey commented on packages/protocol/test/L1/TaikoL1.integration.test.ts
> +        console.log("proposer deployed");
this should be "prover", but do we also want to remove these logs?

2023-02-14 00:18 UTC, cyberhorsey commented on packages/protocol/test/L1/TaikoL1.integration.test.ts
> +            console.log("passed2");
we should remove all of these

2023-02-14 00:23 UTC, cyberhorsey submitted a review, later dismissed

2023-02-14 00:23 UTC, cyberhorsey commented on packages/protocol/test/test_integration.sh
> -  --name $TEST_IMPORT_TEST_ACCOUNT_ETH_JOB_NAME \
dont we still need this if test type is not integration?

2023-02-16 19:42 UTC, RogerLamTd commented
@cyberhorsey I separated the bridge integration tests from the rest of the integration tests, but the build run doesn't include them; I'm not too clear on how to edit that, could you take a look? David believes the occasional integration test failures are from the switching to 2 geth nodes, so this change should prevent that issue.

2023-02-21 15:39 UTC, davidtaikocha approved these changes

2023-02-22 01:38 UTC, cyberhorsey approved these changes

2023-02-22 03:40 UTC, davidtaikocha approved these changes

2023-02-22 03:40 UTC, davidtaikocha approved these changes

2023-02-23 02:44 UTC, dantaik approved these changes

2023-02-23 03:24 UTC, cyberhorsey approved these changes

2023-02-23 03:24 UTC, merged