enhance(protocol): remove redundant check for zero address
taikoxyz/taiko-mono pull request #13083
Opened 2023-02-01 21:49 UTC by d1onys1us

this is already checked by the addressResolved because we pass in `false` to the function. this makes sure it cannot return the zero address.

2023-02-02 00:55 UTC, cyberhorsey commented
I think this should actually be `true` for allowing the 0 address, as we only deploy an EtherVault on Layer 2, not Layer 1?

2023-02-02 02:11 UTC, davidtaikocha commented
> I think this should actually be `true` for allowing the 0 address, as we only deploy an EtherVault on Layer 2, not Layer 1?

I think so.

2023-02-02 08:14 UTC, dantaik requested changes

2023-02-02 08:14 UTC, dantaik commented on packages/protocol/contracts/bridge/libs/LibBridgeProcess.sol
> +        EtherVault(payable(ethVault)).releaseEther(
Good catch, but I think we should have the above change as we do allow the ethVault to be address(0)

2023-02-02 08:14 UTC, dantaik commented on packages/protocol/contracts/bridge/libs/LibBridgeProcess.sol
>          address ethVault = resolver.resolve("ether_vault", false);
```suggestion
        address ethVault = resolver.resolve("ether_vault", true);
```

2023-02-02 22:13 UTC, d1onys1us commented
@dantaik i applied the suggested changes, thanks. but i'm curious, why wasn't this reverting then? it should've been throwing errors when withdrawing on layer 1 right?

2023-02-03 02:19 UTC, davidtaikocha approved these changes

2023-02-03 03:41 UTC, davidtaikocha commented
> @dantaik i applied the suggested changes, thanks. but i'm curious, why wasn't this reverting then? it should've been throwing errors when withdrawing on layer 1 right?

I believe its because the `bool allowZeroAddress` parameter of `AddressReslover.reslove()` function is introduced in [a PR (signal service)](https://github.com/taikoxyz/taiko-mono/commit/53adc983d2cd1fd6d929a06273f5341aacd17645#diff-af382ffb911c4e17a4797dcc2df96a9fde2272b480ab6067b607e4aac5df75b3R58) which is merged after the Alpha-1 release.

2023-02-03 07:17 UTC, dantaik approved these changes

2023-02-03 07:17 UTC, merged