refactor to single component and make pink
taikoxyz/taiko-mono pull request #14074
Opened 2023-06-29 23:13 UTC by d1onys1us

2023-06-29 23:45 UTC, MarcusWentz requested changes
Button is pink in light mode but turns grey in dark mode.

2023-06-29 23:54 UTC, MarcusWentz commented
This button might be good:

https://github.com/taikoxyz/taiko-mono/blob/main/packages/website/components/Hero.tsx#L52-L58

2023-06-30 00:47 UTC, dantaik approved these changes

2023-06-30 05:14 UTC, d1onys1us commented
> This button might be good:
> 
> https://github.com/taikoxyz/taiko-mono/blob/main/packages/website/components/Hero.tsx#L52-L59

addressed your issue. please feel free to merge.

2023-06-30 11:31 UTC, MarcusWentz approved these changes

2023-06-30 11:31 UTC, merged