chore(website): update ecosystem page
taikoxyz/taiko-mono pull request #14162
Opened 2023-07-13 18:49 UTC by d1onys1us

2023-07-13 23:47 UTC, MarcusWentz requested changes

2023-07-13 23:47 UTC, MarcusWentz commented on packages/website/components/EcosystemSection.tsx
> +    icon: "/images/ecosystem/rwbydex.png",
Broken link.
Should be
```
icon: "/images/ecosystem/rwbydex.png",
```

2023-07-13 23:47 UTC, MarcusWentz commented
![render](https://github.com/taikoxyz/taiko-mono/assets/52706599/015a7380-bde2-4a25-b8f5-69e71edf847f)

2023-07-16 06:59 UTC, dantaik submitted a review, later dismissed

2023-07-17 11:06 UTC, 2manslkh commented
I don't see how Taiko was integrated

2023-07-18 10:51 UTC, davidtaikocha submitted a review, later dismissed

2023-07-18 14:26 UTC, d1onys1us commented
> I don't see how Taiko was integrated

updated, the link was wrong for rubydex. also this PR has the right linke for owlto.finance

2023-07-18 14:33 UTC, davidtaikocha approved these changes

2023-07-18 14:39 UTC, MarcusWentz approved these changes

2023-07-18 14:39 UTC, merged

2023-07-21 10:20 UTC, 2manslkh commented
Closes #14173