docs(website): fix broken links
taikoxyz/taiko-mono pull request #14167
Opened 2023-07-14 08:35 UTC by korchinskiiy

broken links

2023-07-14 15:35 UTC, dantaik submitted a review, later dismissed

2023-07-14 15:46 UTC, MarcusWentz commented
I am getting error
```
404 This page could not be found.
```
with the latest build: 
https://website-aikb2ewxl-taikoxyz.vercel.app/docs/guides/build-on-taiko/setup-your-wallet

2023-07-14 15:47 UTC, MarcusWentz requested changes
https://github.com/taikoxyz/taiko-mono/pull/14167#issuecomment-1636047617

2023-07-15 21:29 UTC, d1onys1us approved these changes

2023-07-15 21:40 UTC, MarcusWentz approved these changes

2023-07-15 21:40 UTC, merged