feat(protocol): decouple proof(s) verification from core protocol
taikoxyz/taiko-mono pull request #14221
Opened 2023-07-20 13:47 UTC by adaki2004

This PR separates the proof verification logic.
SGX and other support can come late, and core protocol only sees `bytes`, no `verifierId`.

2023-07-21 15:28 UTC, dantaik commented on packages/protocol/contracts/L1/libs/LibProving.sol
> +                    evidence.verifierId,
we should use delete `evidence.verifierId` and `evidence.proof` from evidence and add a new field called `bytes proofs`. By doing this, the protocol will be agnostic to verifierId which is ZK related. Then you just send `proofs` to the prover contract. 

In side the prover contact, you decode `proofs` into a struct and then further use the `verifiedId` to dispatch zkProofs to zkVerifier.

2023-07-21 15:29 UTC, dantaik commented on packages/protocol/contracts/L1/libs/LibProving.sol
> +                    evidence.verifierId,
In core protocol, no ZK proof info should be exposed.

2023-07-26 12:40 UTC, dantaik commented on packages/protocol/contracts/L1/libs/LibProving.sol
> +                    evidence.verifierId,
Anything else you want to know? I thought it's pretty clear: making sure the core protocol does not know anything about the content of a block proof and how they shall be verified. Move these logics to the Verifier.

2023-07-26 12:42 UTC, dantaik commented
For the core protocol, the proof shall be just a byte array, nothing else. Then the IProofVerifier contract should look like:

```solidity
function verifyBlockProof(uint blockId, bytes calldata blockProof) external;
```

Later we can upgrade the implementation of IProofVerifier and use blockId to perform different verification tasks.

2023-07-27 15:29 UTC, dantaik requested changes

2023-07-27 15:29 UTC, dantaik commented on packages/protocol/contracts/L1/libs/LibProving.sol
> +                    LibBytesUtils.slice(evidence.proofs, 2, 32),
Can we also make `instance` one input variable to `verifyProofs`, then this logic can also be moved to the Verifier. `verifierId` should not be known here at all.

2023-07-27 15:29 UTC, dantaik commented on packages/protocol/contracts/L1/libs/LibProving.sol
> +                    LibBytesUtils.slice(evidence.proofs, 34, 32),
This slice operation also assumes some knowledge of the `proofs` structure. We should move it to the Verifier.

2023-07-27 15:36 UTC, dantaik commented
Please also see https://github.com/taikoxyz/taiko-mono/pull/14221/commits/6e2fb7b23f192a787b7e5f77b7dc98f04a00a246

2023-07-27 22:48 UTC, dantaik commented
> > For the core protocol, the proof shall be just a byte array, nothing else. Then the IProofVerifier contract should look like:
> 
> @dantaik Should not we pass on the instance - within the params - as well? Because i guess this code section also needs to be moved into the ProofVerifier:
> 
> ```
>  if (
>                !LibBytesUtils.equal(
>                    LibBytesUtils.slice(evidence.proof, 0, 32),
>                    bytes.concat(bytes16(0), bytes16(instance))
>                )
>            ) {
>                revert L1_INVALID_PROOF();
>            }
> 
>            if (
>                !LibBytesUtils.equal(
>                    LibBytesUtils.slice(evidence.proof, 32, 32),
>                    bytes.concat(
>                        bytes16(0), bytes16(uint128(uint256(instance)))
>                    )
>                )
>            ) {
>                revert L1_INVALID_PROOF();
>            }
> ```

The idea is that the core protocol should know nothing about the construction of "evidence.proofs" at all.

2023-07-28 18:32 UTC, dantaik approved these changes

2023-07-29 02:14 UTC, davidtaikocha approved these changes

2023-07-29 02:15 UTC, merged