feat(website): add chaindrop to ecosystem page
taikoxyz/taiko-mono pull request #14307
Opened 2023-07-28 10:43 UTC by 2manslkh

Closes #14305

2023-08-01 18:01 UTC, d1onys1us commented
@2manslkh can we take this out of draft? also, do they have a more square / circular icon, would look better for them.

2023-08-02 14:43 UTC, d1onys1us commented on packages/website/components/Ecosystem/EcosystemSection.tsx
> +    name: "Chaindrop Faucet",
this should be above crypton to maintain the alphabetical ordering.

2023-08-02 14:44 UTC, d1onys1us commented on packages/website/components/Ecosystem/EcosystemSection.tsx
> +    link: "chaindrop.org",
this path is broken, i think `https://chaindrop.org` will work. we parse this string to make it look pretty, but we need the valid href link.

2023-08-02 14:44 UTC, d1onys1us requested changes
left some comments

2023-08-07 15:10 UTC, closed without merging

2023-08-07 15:10 UTC, 2manslkh commented
Chaindrop is already added in another PR