docs(website): Update claim-prover-rewards.mdx
taikoxyz/taiko-mono pull request #14368
Opened 2023-08-03 17:48 UTC by IchiCoin

Minor correction regarding TTKOe billing method.

2023-08-04 05:09 UTC, d1onys1us requested changes

2023-08-04 05:09 UTC, d1onys1us commented on packages/website/pages/docs/guides/run-a-node/claim-prover-rewards.mdx
> +Go to the TaikoL1/L2 contract read page ([TTKO](https://sepolia.etherscan.io/address/0x6375394335f34848b850114b66A49D6F47f2cdA8#readProxyContract#F10)/[TTKOe](https://explorer.test.taiko.xyz/address/
```suggestion
Go to the TaikoL1 contract read page ([TTKO](https://sepolia.etherscan.io/address/0x6375394335f34848b850114b66A49D6F47f2cdA8#readProxyContract#F10)/[TTKOe](https://explorer.test.taiko.xyz/address/0x4e7c942D51d977459108bA497FDc71ae0Fc54a00/read-proxy#address-tabs)) and input your prover address to lookup your TTKO/TTKOe claim balance.
```

2023-08-04 05:09 UTC, d1onys1us commented on packages/website/pages/docs/guides/run-a-node/claim-prover-rewards.mdx
> +Go to the TaikoL1/L2 contract read page ([TTKO](https://sepolia.etherscan.io/address/0x6375394335f34848b850114b66A49D6F47f2cdA8#readProxyContract#F10)/[TTKOe](https://explorer.test.taiko.xyz/address/
technically the contract name is TaikoL1 even though that is also deployed on Grimsvotn L2. we might consider renaming the contract to something like TaikoBase.

2023-08-07 12:31 UTC, d1onys1us commented on packages/website/pages/docs/guides/run-a-node/claim-prover-rewards.mdx
> +### Claim TTKO
```suggestion
### Grimsvotn L2
```

2023-08-07 12:32 UTC, d1onys1us commented on packages/website/pages/docs/guides/run-a-node/claim-prover-rewards.mdx
> +### Grimsvotn L2
```suggestion
### Grimsvotn L2 (TTKO)
```

2023-08-07 12:33 UTC, d1onys1us commented on packages/website/pages/docs/guides/run-a-node/claim-prover-rewards.mdx
> +### Eldfell L3
```suggestion
### Eldfell L3 (TTKOe)
```

2023-08-07 12:33 UTC, d1onys1us approved these changes

2023-08-08 01:52 UTC, dantaik approved these changes

2023-08-08 01:53 UTC, merged