feat(website): use cards in guides
taikoxyz/taiko-mono pull request #14378
Opened 2023-08-04 10:48 UTC by 2manslkh

2023-08-04 18:32 UTC, d1onys1us submitted a review, later dismissed

2023-08-04 23:45 UTC, dantaik submitted a review, later dismissed

2023-08-08 02:28 UTC, d1onys1us submitted a review, later dismissed

2023-08-08 13:07 UTC, MarcusWentz requested changes
I see the guide page and tabs are changing inconsistently.

Please remove these changes and open a seperate PR for us to review.

2023-08-09 11:27 UTC, dantaik approved these changes

2023-08-11 02:58 UTC, dantaik submitted a review, later dismissed

2023-08-11 02:59 UTC, dantaik commented
@MarcusWentz @2manslkh This PR is getting old, could you guys work together to resolve pending feedbacks then review it again?

2023-08-11 03:59 UTC, d1onys1us approved these changes

2023-08-11 09:20 UTC, dantaik approved these changes

2023-08-11 12:24 UTC, MarcusWentz approved these changes

2023-08-11 12:24 UTC, merged