feat(website): add goneuron to ecosystem
taikoxyz/taiko-mono pull request #14409
Opened 2023-08-08 09:21 UTC by 2manslkh

Closes #14405

2023-08-08 10:20 UTC, goneuronxyz commented
Something looks a little wonky 
![image](https://github.com/taikoxyz/taiko-mono/assets/141687054/9bae2f54-e137-45ae-b640-3e5821ae11f0)

2023-08-08 13:02 UTC, MarcusWentz requested changes

2023-08-08 13:02 UTC, MarcusWentz commented on packages/website/components/Ecosystem/EcosystemSection.tsx
> +    icon: "/images/ecosystem/goneuron.jepg",
Broken link.

Should be: 
```
goneuron.jpeg
```
instead of 
```
goneuron.jepg
```

2023-08-09 02:31 UTC, MarcusWentz approved these changes

2023-08-09 14:03 UTC, d1onys1us approved these changes

2023-08-09 14:03 UTC, merged

2023-08-09 16:50 UTC, goneuronxyz commented
<3