feat(website): add rubric to ecosystem
taikoxyz/taiko-mono pull request #14591
Opened 2023-08-28 08:12 UTC by 2manslkh

Closes #14584

@IlyaStor Please reopen an issue when Rubric has been integrated on Taiko testnet. Thank you.

2023-08-28 08:41 UTC, d1onys1us approved these changes

2023-08-28 08:42 UTC, d1onys1us commented on packages/website/components/Ecosystem/EcosystemSection.tsx
> +    isLive: false,
```suggestion
    icon: "/images/ecosystem/rubric.png",
    name: "Rubic",
    link: "https://rubic.exchange/",
    description:
      "Rubic enhances interoperability through network bridging and cross-chain dev tools for omnichain dApps. Users access diverse assets via varied DEXs under a unified interface with optimized cross-chain transactions.",
    filters: [],
    isLive: false,
```

2023-08-28 08:43 UTC, d1onys1us commented on packages/website/components/Ecosystem/EcosystemSection.tsx
> +    isLive: false,
can we also rename the file from `rubric.png` -> `rubic.png`

2023-08-28 08:43 UTC, d1onys1us requested changes
look like rubric should be rubic

2023-08-28 23:56 UTC, 2manslkh commented
thanks good catch, fixed

2023-08-30 00:40 UTC, d1onys1us approved these changes

2023-08-30 03:33 UTC, davidtaikocha approved these changes

2023-08-30 03:33 UTC, merged