docs(website): proposer add multiple endpoints for flag PROVER_ENDPOINTS
taikoxyz/taiko-mono pull request #14902
Opened 2023-10-04 16:04 UTC by MarcusWentz

2023-10-04 16:12 UTC, d1onys1us requested changes

2023-10-04 16:41 UTC, MarcusWentz commented on packages/website/pages/docs/guides/enable-a-proposer.mdx
> +  Proposing operation error="failed to propose transactions: unable to find prover"
I will cut the callout and error.

2023-10-05 08:28 UTC, d1onys1us commented on packages/website/pages/docs/guides/enable-a-proposer.mdx
> +PROVER_ENDPOINTS=<PROVER_ENDPOINT_1>:<PROVER_ENDPOINT_2>:<PROVER_ENDPOINT_3>
it is a comma, you can check in the comments of .env.sample of simple-taiko-node 

else lgtm 🙂

2023-10-05 08:42 UTC, dantaik submitted a review, later dismissed

2023-10-05 12:48 UTC, d1onys1us approved these changes

2023-10-05 12:54 UTC, davidtaikocha approved these changes

2023-10-05 12:55 UTC, merged