feat(bridge-ui-v2): add title to toast
taikoxyz/taiko-mono pull request #14962
Opened 2023-10-14 07:02 UTC by xiaodino

Before
![Screen Shot 2023-10-14 at 12 01 54 AM](https://github.com/taikoxyz/taiko-mono/assets/104292916/f66eb3b5-a1f2-4620-ae30-e94b745700aa)

After
![Screen Shot 2023-10-13 at 11 59 58 PM](https://github.com/taikoxyz/taiko-mono/assets/104292916/4b9a62e4-a0f9-4176-80f1-6daefeea08b7)

2023-10-14 09:46 UTC, dantaik submitted a review, later dismissed

2023-10-15 23:03 UTC, KorbinianK requested changes

2023-10-17 17:08 UTC, xiaodino commented on packages/bridge-ui-v2/src/components/NotificationToast/ItemToast.svelte
> +      <div class='callout-bold leading-[24px]'>{@html title}</div>
Good point. Updated.

2023-10-17 17:08 UTC, xiaodino commented on packages/bridge-ui-v2/src/components/Transactions/Status.svelte
> +        '',
Updated. title is required and message is optional.

2023-10-17 17:08 UTC, xiaodino commented on packages/bridge-ui-v2/src/components/NotificationToast/NotificationToast.svelte
> +    duration: 5000,
Updated.

2023-10-17 19:54 UTC, KorbinianK approved these changes

2023-10-18 04:40 UTC, davidtaikocha approved these changes

2023-10-18 04:41 UTC, merged