Add Chainstack provider in 'Run a Taiko node'
taikoxyz/taiko-mono pull request #15013
Opened 2023-10-23 13:34 UTC by soos3d

Hi, I added the instructions on using Chainstack to get an RPC to run a Taiko node (in the same section where Infura and Alchemy are mentioned). 

Full disclosure: I'm a dev advocate at Chainstack.

2023-11-14 11:46 UTC, samui68400 commented
I review it and I find it perfectly clear, bravo

2023-11-22 09:17 UTC, 2manslkh approved these changes

2023-11-22 09:33 UTC, 2manslkh commented on packages/website/package-lock.json
Please uncommit this file

2023-11-22 09:34 UTC, 2manslkh requested changes
remove the package-lock.json file

2023-12-01 03:35 UTC, dantaik commented
Please notice that the website code has been migrated to https://github.com/taikoxyz/website, please submit PRs to the new repository. Thank you.

2023-12-01 03:35 UTC, closed without merging