add rhino.fi to ecosystem
taikoxyz/taiko-mono pull request #15024
Opened 2023-10-24 09:02 UTC by 2manslkh

Closes #15012
Closes #15016

2023-10-24 09:46 UTC, 2manslkh commented
Closes #14982

2023-10-26 00:21 UTC, d1onys1us approved these changes

2023-10-26 05:09 UTC, MarcusWentz requested changes
1. rhinofi.svg logo does not appear in preview.  
2. DotTaiko does not appear (related to alphabetic order maybe?).

2023-10-26 05:12 UTC, MarcusWentz approved these changes

2023-10-26 05:13 UTC, merged