docs(website): Update prover-market-page.mdx
taikoxyz/taiko-mono pull request #15132
Opened 2023-11-04 12:49 UTC by Azkalatihan

Adding my 'Arthas Node' prover

2023-11-05 03:06 UTC, davidtaikocha approved these changes

2023-11-06 03:30 UTC, dantaik approved these changes

2023-11-06 15:20 UTC, MarcusWentz approved these changes

2023-11-06 15:21 UTC, MarcusWentz requested changes
Please resolve merge conflicts.

2023-11-07 10:52 UTC, closed without merging