Update prover-market-page.mdx
taikoxyz/taiko-mono pull request #15148
Opened 2023-11-08 02:22 UTC by zzlnc4

Dear TAIKO Dev,

I have created a domain name http://mikedg-taiko.donkamote.xyz:9876/ for my Taiko Prover endpoint so that it is easier to remember and use by Proposers.

Below is a proof that this dns domain record is resolvable.

Non-authoritative answer:
Name:	mikedg-taiko.donkamote.xyz
Address: 184.174.33.54

Thank you so much and  more power to TAIKO team and project!!!

Sincerely,
mikeDG

2023-11-08 14:05 UTC, RogerLamTd submitted a review, later dismissed

2023-11-09 03:52 UTC, MarcusWentz approved these changes

2023-11-09 03:53 UTC, MarcusWentz requested changes
Please resolve merge conflicts.

2023-11-09 07:08 UTC, RogerLamTd approved these changes

2023-11-12 06:15 UTC, dantaik approved these changes

2023-11-13 05:15 UTC, closed without merging