feat(protocl): Genesis / DeployOnL1 with new proxy upgrades
taikoxyz/taiko-mono pull request #15265
Opened 2023-11-27 06:58 UTC by cyberhorsey

2023-11-28 10:36 UTC, dantaik commented on packages/protocol/genesis/GenerateGenesis.g.sol
> +import "../contracts/common/OwnerUUPSUpgradable.sol";
maybe we can remove imports for 
- OwnerUUPSUpgradable
- AddressManager
- AddressResolver
- IBridge
as they are all indirectly imported by EssentialContract

2023-11-28 10:44 UTC, dantaik commented
@cyberhorsey I made very small changes in this commit, let me know if the code is smaller.

https://github.com/taikoxyz/taiko-mono/pull/15265/commits

2023-11-28 10:45 UTC, dantaik requested changes

2023-11-28 10:45 UTC, dantaik commented on packages/protocol/genesis/GenerateGenesis.g.sol
> +        AddressManager addressManagerProxy =
We should simplify the names buy removing "Proxy", "Singleton"... as all contracts are behnind proxy.

2023-11-28 10:45 UTC, dantaik commented on packages/protocol/utils/generate_genesis/taikoL2.ts
> +            storageLayoutName = contractName
With the latest changes, we don't have `Proxy` or `Singleton` in the name

2023-11-28 10:45 UTC, dantaik commented on packages/protocol/genesis/GenerateGenesis.g.sol
> +        vm.startPrank(addressManager.owner());
For all L2 contracts on mainnet, the owner shall be our security council.

    address public constant MAINNET_SECURITY_COUNCIL = 0x7C50d60743D3FCe5a39FdbF687AFbAe5acFF49Fd;

2023-11-28 11:29 UTC, davidtaikocha commented
> @cyberhorsey I made very small changes in this commit, let me know if the code is smaller.
> 
> https://github.com/taikoxyz/taiko-mono/pull/15265/commits

Looks like this commit didn't fix the size issue:

<img width="1012" alt="image" src="https://github.com/taikoxyz/taiko-mono/assets/104078303/992f6ecf-58f7-4c1b-b4a6-3507f0d7b3ec">

2023-11-29 04:07 UTC, dantaik approved these changes

2023-11-29 04:19 UTC, cyberhorsey commented
@dantaik after merging proxy base back into his branch, tests fail again on TaikoGovernor init function in deploy script. I'll take a look at it tonight.

2023-11-29 04:20 UTC, davidtaikocha commented
> @dantaik after merging proxy base back into his branch, tests fail again on TaikoGovernor init function in deploy script. I'll take a look at it tonight.

i'm looking into it too

2023-11-29 05:26 UTC, cyberhorsey commented
OK, looks good, I will merge now.

2023-11-29 05:26 UTC, merged