Fix typos
taikoxyz/taiko-mono pull request #15311
Opened 2023-12-02 14:33 UTC by nnsW3

hello,
I fixed some typos issues found in your documentation.
Glad that I could help.
Best regards.

2023-12-02 14:43 UTC, dantaik approved these changes

2023-12-04 03:42 UTC, dantaik approved these changes

2023-12-04 03:52 UTC, MarcusWentz approved these changes

2023-12-04 03:53 UTC, MarcusWentz requested changes
Please resolve branch conflicts.

2023-12-04 14:22 UTC, nnsW3 commented
Hello,
I solved them.

2023-12-07 08:40 UTC, dantaik commented
> Hello, I solved them.

Please try again.

2023-12-07 11:53 UTC, closed without merging