chore(bridge-ui-v2): Modal and alerts to inform users about delay for L2->L1 bridging
taikoxyz/taiko-mono pull request #15450
Opened 2024-01-03 16:08 UTC by KorbinianK

WIP

2024-01-03 22:15 UTC, KorbinianK commented on packages/bridge-ui-v2/src/components/WelcomeModal/WelcomeModal.svelte
> +        <a href="https://www.taiko.xyz" target="_blank" class="link">{$t('bridge.welcome_modal.link')} </a>
Where should we link this to?

2024-01-03 23:47 UTC, cyberhorsey approved these changes

2024-01-03 23:48 UTC, cyberhorsey requested changes

2024-01-03 23:48 UTC, cyberhorsey commented on packages/bridge-ui-v2/src/i18n/en.json
> +      "body": "Welcome to <span class='font-bold text-primary-brand'>Katla, our final testnet</span>.<br/>Strengthening security may cause a some delay in L1→L2 bridging, <span class='font-bold text-
this says L1 to L2, should be L2 to L1

2024-01-03 23:54 UTC, KorbinianK commented on packages/bridge-ui-v2/src/i18n/en.json
> +      "body": "Welcome to <span class='font-bold text-primary-brand'>Katla, our final testnet</span>.<br/>Strengthening security may cause a some delay in L1→L2 bridging, <span class='font-bold text-
```suggestion
      "body": "Welcome to <span class='font-bold text-primary-brand'>Katla, our final testnet</span>.<br/>Strengthening security may cause a some delay in L2→L1 bridging, <span class='font-bold text-primary-brand'>around 24 hours</span> on the testnet. We're striving for shorter delays on the mainnet.",
```

2024-01-03 23:54 UTC, KorbinianK commented on packages/bridge-ui-v2/src/i18n/en.json
> +      "slow_bridging": "Please be aware, bridging back to L1 will take around 24hs! Read our Katla announcement for more details."
```suggestion
      "slow_bridging": "Please be aware, bridging back to L1 will take around 24hrs! Read our Katla announcement for more details."
```

2024-01-03 23:55 UTC, KorbinianK commented on packages/bridge-ui-v2/src/i18n/en.json
> +      "body": "Welcome to <span class='font-bold text-primary-brand'>Katla, our final testnet</span>.<br/>Strengthening security may cause a some delay in L1→L2 bridging, <span class='font-bold text-
fixed

2024-01-04 00:26 UTC, cyberhorsey approved these changes

2024-01-04 02:00 UTC, davidtaikocha approved these changes

2024-01-04 02:01 UTC, merged