feat(protocol): added test case for ERC721Airdrop
taikoxyz/taiko-mono pull request #16025
Opened 2024-02-23 19:27 UTC by arularmstrong

This PR adds a test case for ERC721 token airdrop `team/airdrop/ERC721Airdrop.sol`. This addition ensures thorough testing coverage for all supported token standards, enhancing the contract's reliability and functionality.

2024-02-24 01:38 UTC, dantaik requested changes

2024-02-24 01:38 UTC, dantaik commented on packages/protocol/test/team/airdrop/ERC721Airdrop.t.sol
> +import "./LibDelegationSigUtil.sol";
remove this import?

2024-02-24 01:38 UTC, dantaik commented on packages/protocol/test/team/airdrop/ERC721Airdrop.t.sol
> +import "@openzeppelin/contracts-upgradeable/access/OwnableUpgradeable.sol";
use contracts/common/OwnerUUPSUpgradable instead?

2024-02-24 14:53 UTC, dantaik approved these changes

2024-02-25 13:48 UTC, davidtaikocha approved these changes

2024-02-25 13:49 UTC, merged