fix(blobstorage): blockId determination by timestamp
taikoxyz/taiko-mono pull request #16614
Opened 2024-04-02 15:31 UTC by k-kaddal

- Adding a BeaconClient to fetch GenesisTime and SecondPerSlot
- Compute the blockID based on the fetched timestamp

2024-04-02 15:43 UTC, cyberhorsey requested changes

2024-04-02 15:43 UTC, cyberhorsey commented on packages/blobstorage/indexer/indexer.go
> +	BlobsResponse, err := i.beaconClient.getBlobs(ctx, blockID)
can we lowercase this, "blobsResponse", for consistency with other variable names

2024-04-02 23:16 UTC, cyberhorsey approved these changes

2024-04-03 00:20 UTC, dantaik approved these changes

2024-04-03 02:40 UTC, merged