feat(bridge-ui): Update disabled for ChainSelector
taikoxyz/taiko-mono pull request #16814
Opened 2024-04-23 13:44 UTC by monleru

2024-04-23 15:21 UTC, monleru commented
> Before update: Select opens but the change is not active which looks like a bug.
> 
> <img alt="image" width="519" src="https://private-user-images.githubusercontent.com/96314649/324860260-68a2e0f5-6648-4586-a30e-c455b4ffd2a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4ODU5MzMsIm5iZiI6MTcxMzg4NTYzMywicGF0aCI6Ii85NjMxNDY0OS8zMjQ4NjAyNjAtNjhhMmUwZjUtNjY0OC00NTg2LWEzMGUtYzQ1NWI0ZmZkMmE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDE1MjAzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0NjUzYjExYTgzNTA5ZWRjYzEzODYxMmFiYzE4NzEwMWMzYTZlMDZhMmVhNTI3ZjJiYTg2ZDg4MDViOTc5ZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ip-In5B7koQWS8uzYPr3VfxtlI9-DsWZ6Hp9p8Si1o4">
> After the update:
> 
> <img alt="image" width="429" src="https://private-user-images.githubusercontent.com/96314649/324892231-52226c74-6482-4ae6-b671-d10d5a79ac16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4ODU5MzMsIm5iZiI6MTcxMzg4NTYzMywicGF0aCI6Ii85NjMxNDY0OS8zMjQ4OTIyMzEtNTIyMjZjNzQtNjQ4Mi00YWU2LWI2NzEtZDEwZDVhNzlhYzE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDE1MjAzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0ZTJlN2ZjMTJlMjMyNTU3OTAwNTc2ZjJkZDc2ODIwNzE2NDYxNmZiMTc3MzdhMTIxOGFjNWFkYTcwNWQ5N2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZwNwWzAljI4_zMb-KJwZkrenje7JzDn_lxQO6hP_w8o">

2024-04-24 06:51 UTC, KorbinianK requested changes

2024-04-24 06:51 UTC, KorbinianK commented on packages/bridge-ui/src/components/ChainSelectors/ChainPill/ChainPill.svelte
> +  $: disabled = !$account || !$account.isConnected;
```suggestion
  $: disabled = !$account || !$account.isConnected || readOnly;
```

2024-04-24 06:51 UTC, KorbinianK commented on packages/bridge-ui/src/components/ChainSelectors/ChainPill/ChainPill.svelte
>    export let label = '';
```suggestion
  export let label = '';
  export let readOnly = false;
```

Even though `readOnly` is currently unused, please do not remove this functionality.

2024-04-24 07:35 UTC, KorbinianK approved these changes

2024-04-24 07:58 UTC, davidtaikocha approved these changes

2024-04-24 07:59 UTC, merged