fix(eventindexer): nft balance changes should be in db transaction
taikoxyz/taiko-mono pull request #16943
Opened 2024-05-01 02:22 UTC by the-laziest

Increase and subtract of nft balance in db should be done in transaction to prevent corrupted data in case of error between 2 db queries

2024-05-01 04:59 UTC, xiaodino submitted a review, later dismissed
@the-laziest Could you explain more what the PR is for and a way to reproduce the issue?

2024-05-01 14:27 UTC, the-laziest commented
> @the-laziest Could you explain more what the PR is for and a way to reproduce the issue?

Sure, @xiaodino,  if there will be an error for some reason [here](https://github.com/taikoxyz/taiko-mono/blob/215a6001c2c0dc0e8d2d20a438be9889792ff6ef/packages/eventindexer/indexer/index_nft_transfers.go#L135) (related to db connection or smth like that), then in database NFT balance will be increased for `To` address, but not decreased for `From` address

2024-05-01 22:20 UTC, cyberhorsey commented
Two notes:

1) I'm happy to merge this PR, however, we will not use any of this code, and it will be deleted for mainnet (since we will use professional NFT indexing APIs that already exist), so it is not robust on purpose.

2) We can delete the existing `IncreaseBalance` and `SubtractBalance` methods now, since they are unused, so if this PR is to be merged, we should do that.

2024-05-01 23:39 UTC, the-laziest commented
@cyberhorsey, updated all mentioned things

2024-05-01 23:43 UTC, cyberhorsey requested changes

2024-05-01 23:43 UTC, cyberhorsey commented on packages/eventindexer/indexer/index_nft_transfers.go
> +	descreaseOpts := eventindexer.UpdateNFTBalanceOpts{}
typo, should be decrease not descrease

2024-05-01 23:43 UTC, cyberhorsey commented on packages/eventindexer/nft_balance.go
> +	) (*NFTBalance, *NFTBalance, error)
returning two pointers to the same strict here is not clear. we should either give them names return parameters, or wrap them in a parent struct and give each a named member, like "IncreasedNFTBalance" and "DecreasedNFTBalance" on the parent struct of "NFTBalances"

2024-05-01 23:44 UTC, cyberhorsey commented
Left two comments.

2024-05-03 19:51 UTC, the-laziest commented
@cyberhorsey , could you please take a look on it?

2024-05-06 01:45 UTC, cyberhorsey approved these changes

2024-05-06 01:45 UTC, cyberhorsey commented
LGTM. Thanks for doing the requested changes.

2024-05-06 14:43 UTC, dantaik approved these changes

2024-05-06 15:31 UTC, merged

2024-05-06 16:46 UTC, the-laziest commented
@cyberhorsey , can I please ask for contributor poap, if it's applicable to this pr

2024-05-06 19:42 UTC, RogerLamTd commented
@gitpoap-bot please give @the-laziest a poap