fix(relayer): dropdown css and color css fix
taikoxyz/taiko-mono pull request #17000
Opened 2024-05-05 19:49 UTC by ukurenov

2024-05-06 08:58 UTC, KorbinianK commented on packages/bridge-ui/src/components/Faucet/Faucet.svelte
> -      <TokenDropdown {disabled} tokens={mintableTokens} {onlyMintable} bind:value={selectedToken} />
remove this again, it is not meant to be fullscreen.

2024-05-06 08:58 UTC, KorbinianK commented on packages/bridge-ui/src/components/TokenDropdown/DropdownView.svelte
> +  export let isWidthFull: boolean = false;
remove

2024-05-06 08:58 UTC, KorbinianK commented on packages/bridge-ui/src/components/TokenDropdown/DropdownView.svelte
> +    isWidthFull ? 'w-full' : undefined,
remove

2024-05-06 08:58 UTC, KorbinianK requested changes

2024-05-06 08:58 UTC, KorbinianK commented on packages/bridge-ui/src/components/TokenDropdown/TokenDropdown.svelte
> +      {isWidthFull}
remove

2024-05-06 17:19 UTC, KorbinianK approved these changes

2024-05-07 02:37 UTC, dantaik approved these changes

2024-05-07 02:39 UTC, merged