feat(protocol): change to transfer-and-burn pattern with NFT vaults
taikoxyz/taiko-mono pull request #17049
Opened 2024-05-08 14:16 UTC by adaki2004

To remove additional trust assumption, and do not allow vaults (if compromised) to arbitrarily burn tokens. Adapt the ‘transfer and burn’ pattern for NFTs as well (as we did for ERC20).

2024-05-08 14:38 UTC, dantaik requested changes

2024-05-08 14:46 UTC, dantaik commented
@KorbinianK @cyberhorsey I think you guys need to know about this change (similar to what we did to BridgedERC20 vaults). Now you always have to get approvals first before burning bridged NFTs, just like what you do with canonical NFTs.

2024-05-08 14:48 UTC, adaki2004 commented
> @KorbinianK @cyberhorsey I think you guys need to know about this change (similar to what we did to BridgedERC20 vaults). Now you always have to get approvals first before burning bridged NFTs, just like what you do with canonical NFTs.

@KorbinianK 
Yes, so for bridged tokens, while bridging back we now require `approve()` for `erc721` and `setApprovalForAll()` for `erc1155`.

2024-05-08 14:48 UTC, dantaik commented on packages/protocol/contracts/tokenvault/BridgedERC721.sol
>          // Check if the caller is the owner of the token.
```suggestion
        // Check if the caller is the owner of the token. Somehow this is not done inside the _burn() function below.
```

2024-05-08 14:48 UTC, dantaik approved these changes

2024-05-09 06:31 UTC, davidtaikocha approved these changes

2024-05-09 06:31 UTC, merged