feat(nfts): add galxe mapping contract and deploy script
taikoxyz/taiko-mono pull request #17563
Opened 2024-06-12 01:22 UTC by 2manslkh

## Summary
This PR introduces the `RegisterGalxePoints` contract and its corresponding deployment script.

## Changes
- **Smart Contract**: Added `RegisterGalxePoints` contract which allows users to register their addresses.
- **Deployment Script**: Created a deployment script for the `RegisterGalxePoints` contract.
  - To run: `galxe:deploy:mainnet --broadcast`
  - Remove `--broadcast` flag to simulate tx only

## Notes
- Ensure that the `MAINNET_PRIVATE_KEY` env var is set.

2024-06-12 04:03 UTC, dantaik approved these changes

2024-06-13 07:53 UTC, bearni95 requested changes
Please add tests

2024-06-19 10:53 UTC, bearni95 approved these changes

2024-06-25 03:16 UTC, dantaik commented
Shall I merge this PR? pending for 2 weeks already.

2024-06-25 03:35 UTC, 2manslkh commented
merged

2024-06-25 03:35 UTC, merged