feat(bridge): implement a bridge UI
taikoxyz/taiko-mono pull request #176
Opened 2022-10-11 15:02 UTC by shadab-taiko

- Adds API spec file
- Adds create-react-app boilerplate code for bridge UI

2022-11-16 01:35 UTC, cyberhorsey requested changes
it is currently failing lints and i get some errors with `npm start` even though it does run.

```ts
WARNING in ./node_modules/json-rpc-engine/dist/mergeMiddleware.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/jeff/code/taikochain/taiko-mono/packages/bridge-frontend/node_modules/json-rpc-engine/src/mergeMiddleware.ts' file: Error: ENOENT: no such file or directory, open '/home/jeff/code/taikochain/taiko-mono/packages/bridge-frontend/node_modules/json-rpc-engine/src/mergeMiddleware.ts'

WARNING in [eslint] 
src/components/Transactions.tsx
  Line 4:24:  'setTransactions' is assigned a value but never used  @typescript-eslint/no-unused-vars

src/components/tokenSelector/Token.tsx
  Line 15:17:  'isError' is assigned a value but never used    @typescript-eslint/no-unused-vars
  Line 15:26:  'isLoading' is assigned a value but never used  @typescript-eslint/no-unused-vars
```

We should add a husky hook and a github action to lint this new bridge-frontend folder on commit and in CICD

2022-11-16 04:54 UTC, shadab-taiko commented
> 
Fixed the three lint errors.
We can't fix the other sourcemap generation related warnings because those are badly configured typescript config in dependencies of dependencies.

+1 for adding a husky to lint and later to test and the same to CI/CD. Will add a task for this.

2022-11-16 13:39 UTC, shadab-taiko commented
@cyberhorsey  I have added prettier and eslint but haven't been able to configure the precommit hook with husky because of the monorepo nature of the codebase.

2022-11-17 17:46 UTC, cyberhorsey approved these changes

2022-11-18 06:25 UTC, dantaik approved these changes

2022-11-18 07:37 UTC, merged