Featuring SubQuery in docs
taikoxyz/taiko-mono pull request #17739
Opened 2024-07-04 15:09 UTC by sq-ext

2024-07-07 12:03 UTC, swarna1101 requested changes

2024-07-07 12:03 UTC, swarna1101 commented on packages/docs-site/src/content/docs/guides/indexers/overview.md
> +In the context of blockchain and decentralised applications, indexers take on an even more pivotal role. They facilitate streamlined access to on-chain data, encompassing transaction histories, smart
Specify the importance of real-time data and efficiency in the context of Taiko's architecture.

2024-07-07 12:03 UTC, swarna1101 commented on packages/docs-site/src/content/docs/guides/indexers/subquery.md
> +SubQuery is a leading blockchain data indexer that provides developers with fast, flexible, universal, open source and decentralised APIs for web3 projects. SubQuery SDK allows developers to get rich
Highlight specific features of SubQuery that are particularly beneficial for Taiko’s ZK-Rollup architecture, such as handling high throughput and low latency.

2024-07-07 12:03 UTC, swarna1101 commented on packages/docs-site/src/content/docs/guides/indexers/subquery.md
> +
Emphasize the flexibility and control developers have when choosing how to run SubQuery

2024-07-07 12:03 UTC, swarna1101 commented on packages/docs-site/src/content/docs/guides/indexers/subquery.md
> +- Decentralised [SubQuery Network](https://subquery.network/network), the most open, performant, reliable, and scalable data service for dApp developers. The SubQuery Network indexes and services dat
Provide specific examples of how SubQuery’s decentralized network benefits Taiko, such as improved data availability and robustness.

2024-07-11 09:19 UTC, dantaik approved these changes

2024-07-16 00:25 UTC, d1onys1us commented
after discussing with @RogerLamTd this feels a bit off for the core docs. i would recommend adding to the ecosystem page.

2024-07-16 00:25 UTC, closed without merging