feat(nfts): trailblazers s2 badge champion game
taikoxyz/taiko-mono pull request #18040
Opened 2024-09-05 07:51 UTC by bearni95

2024-09-19 02:32 UTC, dantaik requested changes

2024-09-19 02:32 UTC, dantaik commented on packages/nfts/contracts/trailblazers-badges/BadgeChampions.sol
> +        uint256 seed;
use uint64 to make League use only one slot?

2024-09-19 02:32 UTC, dantaik commented on packages/nfts/contracts/trailblazers-badges/BadgeChampions.sol
> +        return abi.encodePacked(_owner, _badgeContract, _tokenId, _leagueId);
why not hash it to bytes32?

2024-09-19 02:32 UTC, dantaik commented on packages/nfts/contracts/trailblazers-badges/BadgeChampions.sol
> +        returns (uint256 openTime, uint256 closeTime, uint256 startTime, uint256 seed)
why not return (League memory league)?

2024-09-19 02:32 UTC, dantaik commented on packages/nfts/contracts/trailblazers-badges/BadgeChampions.sol
> +    modifier leagueOpen(uint256 _leagueId) {
I think all modifiers shall go before functions, can you lint your code and fix all issues?

2024-09-19 02:32 UTC, dantaik commented
I don't know enough about the overall design, so probably ask someone else to review the logics.

2024-10-08 10:48 UTC, KorbinianK approved these changes

2024-10-23 01:30 UTC, dantaik approved these changes

2024-10-23 01:30 UTC, dantaik commented on packages/nfts/contracts/trailblazers-season-2/BadgeMigration.sol
> +import "@openzeppelin/contracts-upgradeable/token/ERC1155/extensions/ERC1155SupplyUpgradeable.sol";
please add new contracts into [gen-layouts.sh](https://github.com/taikoxyz/taiko-mono/blob/main/packages/nfts/deployments/gen-layouts.sh) so we always update the [layout file](https://github.com/taikoxyz/taiko-mono/blob/main/packages/nfts/contract_layout.md) for comparison.

One example: https://github.com/taikoxyz/taiko-mono/pull/18276/files

2024-10-23 01:30 UTC, dantaik commented on packages/nfts/contracts/trailblazers-season-2/TrailblazersBadgesS2.sol
> +        minter = _minter;
why not use `onlyRole`

2024-10-23 04:59 UTC, bennettyong approved these changes

2024-10-30 03:20 UTC, dantaik approved these changes

2024-12-02 09:23 UTC, KorbinianK commented on .github/workflows/guardian-prover-health-check-ui.yml
>    #     vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
this PR shouldn't touch other packages

2024-12-02 09:23 UTC, KorbinianK commented on packages/docs-site/src/content/docs/core-concepts/contestable-rollups.md
this PR shouldn't touch other packages

2024-12-02 09:23 UTC, KorbinianK commented on packages/docs-site/src/content/docs/network-reference/software-releases-and-deployments.md
>  | Package                                                                                | Release notes
this PR shouldn't touch other packages

2024-12-02 09:23 UTC, KorbinianK commented on packages/protocol/contract_layout_layer1.md
this PR shouldn't touch other packages

2024-12-02 09:23 UTC, KorbinianK commented on packages/protocol/contract_layout_layer2.md
this PR shouldn't touch other packages

2024-12-02 11:02 UTC, KorbinianK approved these changes

2024-12-02 11:20 UTC, merged