add aggregated sgx verify test
taikoxyz/taiko-mono pull request #18160
Opened 2024-09-23 01:11 UTC by smtmfft

2024-09-23 13:49 UTC, dantaik approved these changes

2024-09-23 13:49 UTC, dantaik commented on packages/protocol/contracts/layer1/verifiers/SgxVerifier.sol
> +        bytes32[] memory public_inputs = new bytes32[](_ctxs.length + 2);
```suggestion
        bytes32[] memory publicInputs = new bytes32[](_ctxs.length + 2);
```

2024-09-23 13:49 UTC, dantaik commented on packages/protocol/contracts/layer1/verifiers/SgxVerifier.sol
> +        for (uint256 i = 0; i < _ctxs.length; i++) {
```suggestion
        for (uint256 i = 0; i < _ctxs.length; ++i) {
```

2024-09-23 13:49 UTC, dantaik commented on packages/protocol/contracts/layer1/verifiers/SgxVerifier.sol
> +                tran, address(this), newInstance, prover, metaHash, taikoChainId()
use _ctxs[i].metaHash and _ctxs[i].prover directly here?

2024-09-24 11:55 UTC, dantaik requested changes

2024-09-24 11:55 UTC, dantaik commented on packages/protocol/contracts/layer1/verifiers/Risc0Verifier.sol
> +        for (uint256 i = 0; i < _ctxs.length; i++) {
```suggestion
        for (uint256 i; i < _ctxs.length; ++i) {
```

2024-09-24 11:55 UTC, dantaik commented on packages/protocol/contracts/layer1/verifiers/Risc0Verifier.sol
> +            revert RISC_ZERO_INVALID_IMAGE_ID();
use two different error codes?

2024-09-24 14:35 UTC, dantaik approved these changes

2024-09-26 06:27 UTC, YoGhurt111 approved these changes

2024-09-26 06:39 UTC, YoGhurt111 approved these changes

2024-09-26 14:42 UTC, davidtaikocha approved these changes

2024-09-26 14:57 UTC, merged