feat(bridge): bridge design
taikoxyz/taiko-mono pull request #369
Opened 2022-11-30 15:28 UTC by shadab-taiko

2022-11-30 19:01 UTC, cyberhorsey requested changes

2022-11-30 19:01 UTC, cyberhorsey commented on packages/bridge-ui/src/components/form/ProcessingFee.svelte
> +    {#each Array.from($processingFeeDetails) as fee}
this can just be from the domain/fee constant which can replace the store

2022-12-01 18:33 UTC, cyberhorsey submitted a review, later dismissed

2022-12-05 17:26 UTC, RogerLamTd submitted a review, later dismissed

2022-12-06 17:33 UTC, cyberhorsey approved these changes

2022-12-06 17:36 UTC, RogerLamTd approved these changes

2022-12-06 17:36 UTC, merged